{% set name = "comm" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a517ea2ca28931c7007a7a99c562a0fa5883cfb48963140cf642c41c948498be

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - hatchling
  run:
    - python >=3.6
    - traitlets >=5.3

test:
  imports:
    - comm
    - comm.base_comm
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ipython/comm
  summary: Python Comm implementation for the Jupyter kernel protocol
  description: Python Comm implementation for the Jupyter kernel protocol
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://github.com/ipython/comm
  dev_url: https://github.com/ipython/comm

extra:
  recipe-maintainers:
    - martinRenou
